// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ReportMLCI.Data;

#nullable disable

namespace ReportMLCI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260511070404_AddMasterClausesSubDetails")]
    partial class AddMasterClausesSubDetails
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ReportMLCI.Models.MasterClause", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ClauseCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClauseContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClauseTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("MasterClauses");
                });

            modelBuilder.Entity("ReportMLCI.Models.MasterClausesDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<string>("ClauseSubCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ClauseSubContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClauseSubTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MasterClauseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("MasterClauseId1")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MasterClauseId");

                    b.HasIndex("MasterClauseId1");

                    b.ToTable("MasterClausesDetails");
                });

            modelBuilder.Entity("ReportMLCI.Models.MasterClausesSubDetails", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier")
                        .HasDefaultValueSql("NEWID()");

                    b.Property<bool>("IsActive")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<Guid>("MasterClauseDetailId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SubDetailCode")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("SubDetailContent")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SubDetailTitle")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.HasIndex("MasterClauseDetailId");

                    b.ToTable("MasterClausesSubDetails");
                });

            modelBuilder.Entity("ReportMLCI.Models.MasterClausesDetails", b =>
                {
                    b.HasOne("ReportMLCI.Models.MasterClause", null)
                        .WithMany()
                        .HasForeignKey("MasterClauseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ReportMLCI.Models.MasterClause", null)
                        .WithMany("MasterClausesDetails")
                        .HasForeignKey("MasterClauseId1");
                });

            modelBuilder.Entity("ReportMLCI.Models.MasterClausesSubDetails", b =>
                {
                    b.HasOne("ReportMLCI.Models.MasterClausesDetails", null)
                        .WithMany()
                        .HasForeignKey("MasterClauseDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ReportMLCI.Models.MasterClause", b =>
                {
                    b.Navigation("MasterClausesDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
