
	<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWindowsForms>true</UseWindowsForms>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Properties\icon_report.png" />
    <None Remove="ReportMLCIDataSet1.xsd" />
    <None Remove="Reports\Report1.rdlc" />
    <None Remove="Reports\Report_ClauseMLCI.rdlc" />
    <None Remove="Reports\Report_Lampiran1.rdlc" />
    <None Remove="Reports\Report_Lampiran2.rdlc" />
    <None Remove="Reports\SubReport_TtdDebitur.rdlc" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Properties\icon_report.png">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="ReportMLCIDataSet1.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>ReportMLCIDataSet1.Designer.cs</LastGenOutput>
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\Report1.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\ReportEarlyTermination.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\ReportListRejectedCAM.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\ReportHistoryPayment.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\Report_ClauseMLCI.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\Report_Lampiran1.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\ReportListCAMByApprovalDate.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\Report_Lampiran2.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
    <Content Include="Reports\SubReport_TtdDebitur.rdlc">
      <CopyToOutputDirectory>PreserveNewest</CopyToOutputDirectory>
    </Content>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="8.0.22" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.22" />
    <PackageReference Include="ReportViewerCore.WinForms" Version="15.1.26" />
    <PackageReference Include="System.Data.SqlClient" Version="4.8.6" />
    <PackageReference Include="Microsoft.CodeAnalysis.Common" Version="4.8.0" />
    <PackageReference Include="Microsoft.CodeAnalysis.CSharp.Workspaces" Version="4.8.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\ReportMLCI.Shared\ReportMLCI.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
    <Compile Update="ReportMLCIDataSet.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ReportMLCIDataSet.xsd</DependentUpon>
    </Compile>
    <Compile Update="ReportMLCIDataSet1.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ReportMLCIDataSet1.xsd</DependentUpon>
    </Compile>
    <Compile Update="Reports\DatasetDummyMLCI.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>DatasetDummyMLCI.xsd</DependentUpon>
    </Compile>
    <Compile Update="Reports\ProdukDataset.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>ProdukDataset.xsd</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <None Update="ReportMLCIDataSet.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>ReportMLCIDataSet.Designer.cs</LastGenOutput>
    </None>
    <None Update="Reports\DatasetDummyMLCI.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>DatasetDummyMLCI.Designer.cs</LastGenOutput>
    </None>
    <None Update="Reports\ProdukDataset.xsd">
      <Generator>MSDataSetGenerator</Generator>
      <LastGenOutput>ProdukDataset.Designer.cs</LastGenOutput>
    </None>
  </ItemGroup>

</Project>